### ISSUE TITLE
CUDA 11.8 migration should remove the 11.2 build?

### ISSUE THREAD

**Issue by leofang** [conda-forge/nccl-feedstock#102]
Right now, for each arch we have 3 pipelines: CUDA 11.2, 11.8, and 12.0. I think the 11.2 one should be removed. @jakirkham thoughts?

**Comment by jakirkham** [comment]
Would prefer to leave it. There are still cases where the CUDA 11.2 builds are useful

**Comment by leofang** [comment]
I am not sure why it is, given that we've switched to [statically link to cudart](https://github.com/conda-forge/nccl-feedstock/blob/8e630ad51be3ff282dac96ea86d46086e59c9e89/recipe/build.sh#L3). If a library is statically linked to cudart, minor version compatibility would kick in and the CUDA 11.8 build can still serve 11.2 users. Furthermore, the CUDA 11.2 build would not offer feature parity with the official release (ex: stream capture does not work #62).

**Comment by jakirkham** [comment]
As we have now dropped CUDA 11.2 in conda-forge ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/5339 ), this should happen automatically on the next re-render

**Comment by leofang** [comment]
> this should happen automatically on the next re-render

It seems to have happened in #110, closing. Thanks all!
