### ISSUE TITLE
Add `conda-forge/cuda` as maintainers?

### ISSUE THREAD

**Issue by leofang** [conda-forge/nccl-feedstock#112]

**Comment by bdice** [comment]
Yes, I support this. We've been doing the same for many other NVIDIA feedstocks. I'll go ahead and file a bot PR for that.

**Comment by leofang** [comment]
done in #115

**Comment by leofang** [comment]
For some reason #115 did not add the team...

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
nvm it seems the web UI https://github.com/orgs/conda-forge/teams would not list a team under the team member list, but it does work already (ex: #116 pinged the entire `cuda` team for review). Closing.
