### ISSUE TITLE
wrong run export

### ISSUE THREAD

**Issue by beckermr** [conda-forge/nccl-feedstock#36]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

It appears we have a run export on 'x', but the global pin is specified down to 'x.x.x.x'. 

We had to do a global migration recently from 2.7.8.1 to 2.8.4.1. See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1245

This doesn't make sense if the compatibility is really at 'x'. 

We are either over pinning in places or we need a tighter run export and global pin. 

cc @leofang @jakirkham @kkraus14 @CJ-Wright

**Comment by beckermr** [comment]
xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/309

feel free to close this issue if ppl like things the way they are.

**Comment by jakirkham** [comment]
I think we were trying to line this up with RAPIDS, which does pin this tightly. Also I don't think this is tracked by ABI lab so we were being cautious

**Comment by jakirkham** [comment]
cc @mike-wendt (in case you have thoughts here)

**Comment by jakirkham** [comment]
Also cc @dantegd @cjnollet as I think you may have more experience using this library directly

**Comment by kkraus14** [comment]
I'm not sure if nccl follows strict semantic versioning. Will ping the team internally to get their thoughts on this.

**Comment by leofang** [comment]
I was under impression that we need the exact pinning here because of lack of semantic versioning, but I could be wrong ￼

**Comment by kkraus14** [comment]
Got confirmation internally that NCCL does follow semantic versioning so we should be safe just pinning to 2.x.x.x.

Sounds like we should update the global pinning to just `2`.

**Comment by kkraus14** [comment]
Closing as this is not an issue in the feedstock. We need to fix the pinning in the global pinnings though.

**Comment by jakirkham** [comment]
PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1292 ) should fix the global pinnings and close out the migration. Please take a look (have cc'd everyone from this thread there) 🙂
