### ISSUE TITLE
License hyperlink on anaconda.org not working

### ISSUE THREAD

**Issue by leofang** [conda-forge/nccl-feedstock#61]
This hyperlink on anaconda.org does not correctly jump to `license_url` set in `meta.yaml`:
<img width="737" alt="截圖 2022-01-05 下午3 26 04" src="https://user-images.githubusercontent.com/5534781/148284314-02c4b0e2-7f05-4ba0-81fd-9d1787e1d315.png">

**Comment by jakirkham** [comment]
Thanks Leo! 😄

Looks like this recipe doesn't have `license_url`. Only seeing these `license*` fields:

https://github.com/conda-forge/nccl-feedstock/blob/c5c8ca2f021ad10055b76b1ca11177350c2fe0aa/recipe/meta.yaml#L42-L44

**Comment by leofang** [comment]
hmm I swear I saw that... But yes you're right John, closing.

**Comment by jakirkham** [comment]
No worries. We could still leave open if we want to add this though
