### ISSUE TITLE
NCCL 2.13.4 for aarch64 was not released

### ISSUE THREAD

**Issue by leofang** [conda-forge/nccl-feedstock#74]
#71 kept hitting timeout so I bumped the limit in #73, but it still could not complete:
https://app.travis-ci.com/github/conda-forge/nccl-feedstock/builds/254106834

**Comment by leofang** [comment]
I do no have time to work on this in the next few days, so opening a ticket to track in case I forgot.

**Comment by jakirkham** [comment]
Tried restarting a few times today without luck. Also tried using [the custom build trigger]( https://blog.travis-ci.com/2017-08-24-trigger-custom-build ) in case there was something odd with that job.

After a cursory look, am not seeing this failure showing up for other feedstocks. So wondering if maybe [the `travis_wait` command]( https://github.com/conda-forge/nccl-feedstock/blob/c3f897f4a92010738799c6495ad6a64c4baccbe8/.travis.yml#L32 ) is not working as expected.

Also wondering if we should just move this job to Azure. It appears the `ppc64le` job is already there.

**Comment by leofang** [comment]
Thanks, John! #76 works.

**Comment by jakirkham** [comment]
Great! Tried restarting a few times. Guessing you did. Glad we got them all out eventually.
